name: Go Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  EACHMODULE_CONCURRENCY: 2

jobs:
  build:
    name: Build SDK 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.19, 1.18]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Test
      run: make build
